package com.jarana.entities;
// Generated Mar 12, 2017 11:10:29 PM by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "Customer", catalog = "ecommv2")
public class Customer implements java.io.Serializable {

	private String cuEmail;
	private String cuPassword;
	private String cuFirstNm;
	private String cuLastNm;
	private String cuDob;
	private char cuGender;
	private String cuAddress;
	private String cuCity;
	private String cuState;
	private Integer cuZipCode;
	private String cuTelephone;
	private Set<InvoiceHeader> invoiceHeaders = new HashSet<InvoiceHeader>(0);
	private Set<InvoiceDetail> invoiceDetails = new HashSet<InvoiceDetail>(0);

	public Customer() {
	}

	public Customer(String cuEmail, String cuPassword, String cuDob, char cuGender) {
		this.cuEmail = cuEmail;
		this.cuPassword = cuPassword;
		this.cuDob = cuDob;
		this.cuGender = cuGender;
	}

	public Customer(String cuEmail, String cuPassword, String cuFirstNm, String cuLastNm, String cuDob, char cuGender,
			String cuAddress, String cuCity, String cuState, Integer cuZipCode, String cuTelephone,
			Set<InvoiceHeader> invoiceHeaders, Set<InvoiceDetail> invoiceDetails) {
		this.cuEmail = cuEmail;
		this.cuPassword = cuPassword;
		this.cuFirstNm = cuFirstNm;
		this.cuLastNm = cuLastNm;
		this.cuDob = cuDob;
		this.cuGender = cuGender;
		this.cuAddress = cuAddress;
		this.cuCity = cuCity;
		this.cuState = cuState;
		this.cuZipCode = cuZipCode;
		this.cuTelephone = cuTelephone;
		this.invoiceHeaders = invoiceHeaders;
		this.invoiceDetails = invoiceDetails;
	}

	@Id

	@Column(name = "cu_email", unique = true, nullable = false, length = 35)
	public String getCuEmail() {
		return this.cuEmail;
	}

	public void setCuEmail(String cuEmail) {
		this.cuEmail = cuEmail;
	}

	@Column(name = "cu_password", nullable = false, length = 15)
	public String getCuPassword() {
		return this.cuPassword;
	}

	public void setCuPassword(String cuPassword) {
		this.cuPassword = cuPassword;
	}

	@Column(name = "cu_first_nm", length = 40)
	public String getCuFirstNm() {
		return this.cuFirstNm;
	}

	public void setCuFirstNm(String cuFirstNm) {
		this.cuFirstNm = cuFirstNm;
	}

	@Column(name = "cu_last_nm", length = 40)
	public String getCuLastNm() {
		return this.cuLastNm;
	}

	public void setCuLastNm(String cuLastNm) {
		this.cuLastNm = cuLastNm;
	}

	@Column(name = "cu_dob", nullable = false, length = 10)
	public String getCuDob() {
		return this.cuDob;
	}

	public void setCuDob(String cuDob) {
		this.cuDob = cuDob;
	}

	@Column(name = "cu_gender", nullable = false, length = 1)
	public char getCuGender() {
		return this.cuGender;
	}

	public void setCuGender(char cuGender) {
		this.cuGender = cuGender;
	}

	@Column(name = "cu_address")
	public String getCuAddress() {
		return this.cuAddress;
	}

	public void setCuAddress(String cuAddress) {
		this.cuAddress = cuAddress;
	}

	@Column(name = "cu_city", length = 25)
	public String getCuCity() {
		return this.cuCity;
	}

	public void setCuCity(String cuCity) {
		this.cuCity = cuCity;
	}

	@Column(name = "cu_state", length = 2)
	public String getCuState() {
		return this.cuState;
	}

	public void setCuState(String cuState) {
		this.cuState = cuState;
	}

	@Column(name = "cu_zip_code")
	public Integer getCuZipCode() {
		return this.cuZipCode;
	}

	public void setCuZipCode(Integer cuZipCode) {
		this.cuZipCode = cuZipCode;
	}

	@Column(name = "cu_telephone", length = 16)
	public String getCuTelephone() {
		return this.cuTelephone;
	}

	public void setCuTelephone(String cuTelephone) {
		this.cuTelephone = cuTelephone;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<InvoiceHeader> getInvoiceHeaders() {
		return this.invoiceHeaders;
	}

	public void setInvoiceHeaders(Set<InvoiceHeader> invoiceHeaders) {
		this.invoiceHeaders = invoiceHeaders;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<InvoiceDetail> getInvoiceDetails() {
		return this.invoiceDetails;
	}

	public void setInvoiceDetails(Set<InvoiceDetail> invoiceDetails) {
		this.invoiceDetails = invoiceDetails;
	}

}
