package com.jarana.entities;
// Generated Mar 12, 2017 11:10:29 PM by Hibernate Tools 5.2.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InvoiceHeader generated by hbm2java
 */
@Entity
@Table(name = "Invoice_Header", catalog = "ecommv2")
public class InvoiceHeader implements java.io.Serializable {

	private Long ihInvNb;
	private Customer customer;
	private Date ihInvDt;
	private BigDecimal ihTotalAm;
	private Set<InvoiceDetail> invoiceDetails = new HashSet<InvoiceDetail>(0);

	public InvoiceHeader() {
	}

	public InvoiceHeader(Customer customer, Date ihInvDt, BigDecimal ihTotalAm) {
		this.customer = customer;
		this.ihInvDt = ihInvDt;
		this.ihTotalAm = ihTotalAm;
	}

	public InvoiceHeader(Customer customer, Date ihInvDt, BigDecimal ihTotalAm, Set<InvoiceDetail> invoiceDetails) {
		this.customer = customer;
		this.ihInvDt = ihInvDt;
		this.ihTotalAm = ihTotalAm;
		this.invoiceDetails = invoiceDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ih_inv_nb", unique = true, nullable = false)
	public Long getIhInvNb() {
		return this.ihInvNb;
	}

	public void setIhInvNb(Long ihInvNb) {
		this.ihInvNb = ihInvNb;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ih_custmr_id", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ih_inv_dt", nullable = false, length = 19)
	public Date getIhInvDt() {
		return this.ihInvDt;
	}

	public void setIhInvDt(Date ihInvDt) {
		this.ihInvDt = ihInvDt;
	}

	@Column(name = "ih_total_am", nullable = false, precision = 10, scale = 4)
	public BigDecimal getIhTotalAm() {
		return this.ihTotalAm;
	}

	public void setIhTotalAm(BigDecimal ihTotalAm) {
		this.ihTotalAm = ihTotalAm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "invoiceHeader")
	public Set<InvoiceDetail> getInvoiceDetails() {
		return this.invoiceDetails;
	}

	public void setInvoiceDetails(Set<InvoiceDetail> invoiceDetails) {
		this.invoiceDetails = invoiceDetails;
	}

}
