package com.jarana.entities;
// Generated Mar 12, 2017 11:10:29 PM by Hibernate Tools 5.2.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Part generated by hbm2java
 */
@Entity
@Table(name = "Part", catalog = "ecommv2", uniqueConstraints = @UniqueConstraint(columnNames = "pa_part_nb"))
public class Part implements java.io.Serializable {

	private Long paSkuNb;
	private Vendor vendor;
	private String paPartNb;
	private String paDescription;
	private String paCatgryNm;
	private BigDecimal paCostAm;
	private BigDecimal paPriceAm;
	private Set<Inventory> inventories = new HashSet<Inventory>(0);
	private Set<PoDetail> poDetails = new HashSet<PoDetail>(0);
	private Set<InvoiceDetail> invoiceDetails = new HashSet<InvoiceDetail>(0);

	public Part() {
	}

	public Part(Vendor vendor, String paPartNb, String paCatgryNm) {
		this.vendor = vendor;
		this.paPartNb = paPartNb;
		this.paCatgryNm = paCatgryNm;
	}

	public Part(Vendor vendor, String paPartNb, String paDescription, String paCatgryNm, BigDecimal paCostAm,
			BigDecimal paPriceAm, Set<Inventory> inventories, Set<PoDetail> poDetails,
			Set<InvoiceDetail> invoiceDetails) {
		this.vendor = vendor;
		this.paPartNb = paPartNb;
		this.paDescription = paDescription;
		this.paCatgryNm = paCatgryNm;
		this.paCostAm = paCostAm;
		this.paPriceAm = paPriceAm;
		this.inventories = inventories;
		this.poDetails = poDetails;
		this.invoiceDetails = invoiceDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "pa_sku_nb", unique = true, nullable = false)
	public Long getPaSkuNb() {
		return this.paSkuNb;
	}

	public void setPaSkuNb(Long paSkuNb) {
		this.paSkuNb = paSkuNb;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pa_vendor_nb", nullable = false)
	public Vendor getVendor() {
		return this.vendor;
	}

	public void setVendor(Vendor vendor) {
		this.vendor = vendor;
	}

	@Column(name = "pa_part_nb", unique = true, nullable = false, length = 12)
	public String getPaPartNb() {
		return this.paPartNb;
	}

	public void setPaPartNb(String paPartNb) {
		this.paPartNb = paPartNb;
	}

	@Column(name = "pa_description")
	public String getPaDescription() {
		return this.paDescription;
	}

	public void setPaDescription(String paDescription) {
		this.paDescription = paDescription;
	}

	@Column(name = "pa_catgry_nm", nullable = false, length = 15)
	public String getPaCatgryNm() {
		return this.paCatgryNm;
	}

	public void setPaCatgryNm(String paCatgryNm) {
		this.paCatgryNm = paCatgryNm;
	}

	@Column(name = "pa_cost_am", precision = 10, scale = 4)
	public BigDecimal getPaCostAm() {
		return this.paCostAm;
	}

	public void setPaCostAm(BigDecimal paCostAm) {
		this.paCostAm = paCostAm;
	}

	@Column(name = "pa_price_am", precision = 10, scale = 4)
	public BigDecimal getPaPriceAm() {
		return this.paPriceAm;
	}

	public void setPaPriceAm(BigDecimal paPriceAm) {
		this.paPriceAm = paPriceAm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "part")
	public Set<Inventory> getInventories() {
		return this.inventories;
	}

	public void setInventories(Set<Inventory> inventories) {
		this.inventories = inventories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "part")
	public Set<PoDetail> getPoDetails() {
		return this.poDetails;
	}

	public void setPoDetails(Set<PoDetail> poDetails) {
		this.poDetails = poDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "part")
	public Set<InvoiceDetail> getInvoiceDetails() {
		return this.invoiceDetails;
	}

	public void setInvoiceDetails(Set<InvoiceDetail> invoiceDetails) {
		this.invoiceDetails = invoiceDetails;
	}

}
