package com.jarana.entities;
// Generated Mar 12, 2017 11:10:29 PM by Hibernate Tools 5.2.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PoDetail generated by hbm2java
 */
@Entity
@Table(name = "PO_Detail", catalog = "ecommv2")
public class PoDetail implements java.io.Serializable {

	private PoDetailId id;
	private PoHeader poHeader;
	private Part part;
	private Vendor vendor;
	private Date pdPoDt;
	private String pdCatgryNm;
	private int pdPoQy;
	private BigDecimal pdCostAm;
	private BigDecimal pdSubtotAm;

	public PoDetail() {
	}

	public PoDetail(PoDetailId id, PoHeader poHeader, Part part, Vendor vendor, Date pdPoDt, String pdCatgryNm,
			int pdPoQy, BigDecimal pdCostAm, BigDecimal pdSubtotAm) {
		this.id = id;
		this.poHeader = poHeader;
		this.part = part;
		this.vendor = vendor;
		this.pdPoDt = pdPoDt;
		this.pdCatgryNm = pdCatgryNm;
		this.pdPoQy = pdPoQy;
		this.pdCostAm = pdCostAm;
		this.pdSubtotAm = pdSubtotAm;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "pdPoNb", column = @Column(name = "pd_po_nb", nullable = false)),
			@AttributeOverride(name = "pdSkuNb", column = @Column(name = "pd_sku_nb", nullable = false)) })
	public PoDetailId getId() {
		return this.id;
	}

	public void setId(PoDetailId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pd_po_nb", nullable = false, insertable = false, updatable = false)
	public PoHeader getPoHeader() {
		return this.poHeader;
	}

	public void setPoHeader(PoHeader poHeader) {
		this.poHeader = poHeader;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pd_sku_nb", nullable = false, insertable = false, updatable = false)
	public Part getPart() {
		return this.part;
	}

	public void setPart(Part part) {
		this.part = part;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pd_vendor_nb", nullable = false)
	public Vendor getVendor() {
		return this.vendor;
	}

	public void setVendor(Vendor vendor) {
		this.vendor = vendor;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "pd_po_dt", nullable = false, length = 19)
	public Date getPdPoDt() {
		return this.pdPoDt;
	}

	public void setPdPoDt(Date pdPoDt) {
		this.pdPoDt = pdPoDt;
	}

	@Column(name = "pd_catgry_nm", nullable = false, length = 15)
	public String getPdCatgryNm() {
		return this.pdCatgryNm;
	}

	public void setPdCatgryNm(String pdCatgryNm) {
		this.pdCatgryNm = pdCatgryNm;
	}

	@Column(name = "pd_po_qy", nullable = false)
	public int getPdPoQy() {
		return this.pdPoQy;
	}

	public void setPdPoQy(int pdPoQy) {
		this.pdPoQy = pdPoQy;
	}

	@Column(name = "pd_cost_am", nullable = false, precision = 10, scale = 4)
	public BigDecimal getPdCostAm() {
		return this.pdCostAm;
	}

	public void setPdCostAm(BigDecimal pdCostAm) {
		this.pdCostAm = pdCostAm;
	}

	@Column(name = "pd_subtot_am", nullable = false, precision = 10, scale = 4)
	public BigDecimal getPdSubtotAm() {
		return this.pdSubtotAm;
	}

	public void setPdSubtotAm(BigDecimal pdSubtotAm) {
		this.pdSubtotAm = pdSubtotAm;
	}

}
