package com.jarana.entities;
// Generated Mar 12, 2017 11:10:29 PM by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PoDetailId generated by hbm2java
 */
@Embeddable
public class PoDetailId implements java.io.Serializable {

	private long pdPoNb;
	private long pdSkuNb;

	public PoDetailId() {
	}

	public PoDetailId(long pdPoNb, long pdSkuNb) {
		this.pdPoNb = pdPoNb;
		this.pdSkuNb = pdSkuNb;
	}

	@Column(name = "pd_po_nb", nullable = false)
	public long getPdPoNb() {
		return this.pdPoNb;
	}

	public void setPdPoNb(long pdPoNb) {
		this.pdPoNb = pdPoNb;
	}

	@Column(name = "pd_sku_nb", nullable = false)
	public long getPdSkuNb() {
		return this.pdSkuNb;
	}

	public void setPdSkuNb(long pdSkuNb) {
		this.pdSkuNb = pdSkuNb;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PoDetailId))
			return false;
		PoDetailId castOther = (PoDetailId) other;

		return (this.getPdPoNb() == castOther.getPdPoNb()) && (this.getPdSkuNb() == castOther.getPdSkuNb());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getPdPoNb();
		result = 37 * result + (int) this.getPdSkuNb();
		return result;
	}

}
