package com.jarana.entities;
// Generated Mar 12, 2017 11:10:29 PM by Hibernate Tools 5.2.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PoHeader generated by hbm2java
 */
@Entity
@Table(name = "PO_Header", catalog = "ecommv2")
public class PoHeader implements java.io.Serializable {

	private Long phPoNb;
	private Vendor vendor;
	private Date phPoDt;
	private BigDecimal phTotalAm;
	private Set<PoDetail> poDetails = new HashSet<PoDetail>(0);

	public PoHeader() {
	}

	public PoHeader(Vendor vendor, Date phPoDt, BigDecimal phTotalAm) {
		this.vendor = vendor;
		this.phPoDt = phPoDt;
		this.phTotalAm = phTotalAm;
	}

	public PoHeader(Vendor vendor, Date phPoDt, BigDecimal phTotalAm, Set<PoDetail> poDetails) {
		this.vendor = vendor;
		this.phPoDt = phPoDt;
		this.phTotalAm = phTotalAm;
		this.poDetails = poDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ph_po_nb", unique = true, nullable = false)
	public Long getPhPoNb() {
		return this.phPoNb;
	}

	public void setPhPoNb(Long phPoNb) {
		this.phPoNb = phPoNb;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ph_vendor_nb", nullable = false)
	public Vendor getVendor() {
		return this.vendor;
	}

	public void setVendor(Vendor vendor) {
		this.vendor = vendor;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ph_po_dt", nullable = false, length = 19)
	public Date getPhPoDt() {
		return this.phPoDt;
	}

	public void setPhPoDt(Date phPoDt) {
		this.phPoDt = phPoDt;
	}

	@Column(name = "ph_total_am", nullable = false, precision = 10, scale = 4)
	public BigDecimal getPhTotalAm() {
		return this.phTotalAm;
	}

	public void setPhTotalAm(BigDecimal phTotalAm) {
		this.phTotalAm = phTotalAm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "poHeader")
	public Set<PoDetail> getPoDetails() {
		return this.poDetails;
	}

	public void setPoDetails(Set<PoDetail> poDetails) {
		this.poDetails = poDetails;
	}

}
